name: Build Plugin
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:
          - "11.2.1"
          - "11.3.2"
          - "11.4.3"
          - "12.0.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Ghidra Action
        uses: antoniovazquezblanco/setup-ghidra@v2.0.12
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}
      - name: Build
        run: gradle buildExtension
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GhidraMetrics_${{ matrix.ghidra }}
          path: dist/*.zip
  release:
    runs-on: ubuntu-latest
    needs: build-plugin
    if: contains(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: GhidraMetrics_*/*.zip
